language: node_js
node_js:
  - "9.3.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm install -g yarn --cache-min 999999999
install:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
